# Generated by Django 4.2.3 on 2023-08-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.CharField(max_length=100)),
                ('Actors', models.CharField(max_length=100)),
                ('Actress', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('imdbRating', models.IntegerField()),
                ('Runtime', models.IntegerField()),
            ],
        ),
    ]
